import numpy as np

# use chain indices instead of residue names to identify electrode...
cathode_index=(0,4); anode_index=(3,7) # note chain indices start at 0 ...
# list of Nanotubes ..
NanoTubes = [(1,5),(2,6)]
# for now , must input nanotube axis.  Eventually, write code to automatically determine this...
nanotube_axis=[(1.0, 0.0, 0.0), (-0.5, np.sqrt(3)/2.0, 0.0) ]  # axis in cartesian coordinates, not box vectors ...

